version: '3.8'

networks:
  inception_network:
    driver: bridge
    name: inception_network

# TODO: implement volume binding on specific folder
volumes:
  db:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/${USER}/Documents/inception/srcs/volumes/db
    #   o: bind
  wordpress:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/${USER}/Documents/inception/srcs/volumes/wordpress
    #   o: bind

# TODO: use secrets instead of env_file or environment

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: ${MARIA_DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIA_DB_DATABASE_NAME}
      MYSQL_USER:  ${MARIA_DB_USER}
      MYSQL_PASSWORD: ${MARIA_DB_PASSWORD}
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile
    ports:
      - "443:443" # host-port:docker-port
    env_file:
      - .env
    environment:
      - DOMAIN=${WORDPRESS_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - nginx
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: localhost:3306
      WORDPRESS_DB_USER: ${MARIA_DB_ROOT_USER}
      WORDPRESS_DB_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIA_DB_DATABASE_NAME}
      NORMAL_USER: ${WORDPRESS_USER}
      NORMAL_PASSWORD: ${WORDPRESS_PASSWORD}
      NORMAL_EMAIL: ${WORDPRESS_EMAIL}
      ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      PAGE_TITLE: ${WORDPRESS_PAGE_TITLE}
      HOST: ${WORDPRESS_HOST}
      PORT: ${WORDPRESS_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
