version: '3.8'

networks:
  inception_network:

# TODO: implement volume binding on specific folder
volumes:
  db:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/${USER}/Documents/inception/srcs/volumes/db
    #   o: bind
  wordpress:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/${USER}/Documents/inception/srcs/volumes/wordpress
    #   o: bind

# TODO: use secrets instead of env_file or environment

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db:/var/lib/mysql
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 3
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile
    ports:
      - "443:443" # host-port:docker-port
      - "80:80"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - nginx
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
