version: '3.8'

networks:
  inception_network:

# TODO: implement volume binding on specific folder
volumes:
  db:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data
    #   o: bind
  wordpress:
    driver: local
    # driver_opts:
    #   type: none
    #   device: /home/${USER}/data
    #   o: bind

# TODO: use secrets instead of env_file or environment

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db:/var/lib/mysql
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - MARIA_DB_ROOT_USER=${MARIA_DB_ROOT_USER}
      - MARIA_DB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MARIA_DB_DATABASE_NAME=${MARIA_DB_DATABASE_NAME}
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile
    ports:
      - "443:443" # host-port:docker-port
    depends_on:
      - wordpress
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MARIA_DB_ROOT_USER=${MARIA_DB_ROOT_USER}
      - MARIA_DB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MARIA_DB_DATABASE_NAME=${MARIA_DB_DATABASE_NAME}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_TEST_USER=${WORDPRESS_TEST_USER}
      - WORDPRESS_TEST_USER_PASSWORD=${WORDPRESS_TEST_USER_PASSWORD}
      - WORDPRESS_TEST_USER_EMAIL=${WORDPRESS_TEST_USER_EMAIL}
  ftp:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/bonus/ftp'
      dockerfile: Dockerfile
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
        - FTP_DIRECTORY=${FTP_DIRECTORY}
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    depends_on:
      mariadb:
        condition: service_healthy
      nginx:
        condition: service_started
  adminer:
    image: adminer # TODO: replace with custom image with adminer
    restart: always
    networks:
      - inception_network
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy






  # grafana:
  #   restart: always
  #   networks:
  #     - inception_network
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy
  # prometheus:
  #   image: prom/prometheus
  #   restart: always
  #   networks:
  #     - inception_network
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"