version: '3.8'

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_USER}
      MYSQL_DATABASE: ${MARIA_DB_DATABASE}
      MYSQL_USER:  ${MARIA_DB_USER}
      MYSQL_PASSWORD: ${MARIA_DB_PASSWORD}
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_vol:/var/www/html
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile
    ports:
      - "443:80" # host-port:docker-port
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_vol:/var/www/html
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      - nginx
      - mariadb

networks:
  inception_network:
    driver: bridge
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/db_volume
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/wordpress_volume
      o: bind
    
