version: '3.8'

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db
    environment:
      MYSQL_ROOT_USER: ${MARIA_DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_ROOT_USER}
      MYSQL_DATABASE: ${MARIA_DB_DATABASE_NAME}
      MYSQL_USER:  ${MARIA_DB_USER}
      MYSQL_PASSWORD: ${MARIA_DB_PASSWORD}
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
    env_file:
      - .env
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile
    ports:
      - "443:80" # host-port:docker-port
    env_file:
      - .env
    depends_on:
      - mariadb
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      - nginx
      - mariadb
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MARIA_DB_ROOT_USER}
      WORDPRESS_DB_PASSWORD: ${MARIA_DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MARIA_DB_DATABASE_NAME}
      NORMAL_USER: ${WORDPRESS_USER}
      NORMAL_PASSWORD: ${WORDPRESS_PASSWORD}
      ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      HOST: ${WORDPRESS_HOST}
      PORT: ${WORDPRESS_PORT}


networks:
  inception_network:
    driver: bridge
    name: inception_network
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/${whoami}/Documents/inception/srcs/volumes/db_volume
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/${whoami}/Documents/inception/srcs/volumes/wordpress_volume
      o: bind
    
