version: '3.8'

services:
  mariadb:
    restart: always
    networks:
      - inception_network
    volumes:
      - db
    build:
      context: './requirements/mariadb'
      dockerfile: Dockerfile
  wordpress:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_vol:wordpress/
    build:
      context: './requirements/wordpress'
      dockerfile: Dockerfile
    depends_on:
      - mariadb
  nginx:
    restart: always
    networks:
      - inception_network
    volumes:
      - wordpress_vol
    build:
      context: './requirements/nginx'
      dockerfile: Dockerfile

networks:
  inception_network:
    driver: bridge
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./db_volume
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: ./wordpress_volume
      o: bind
    
