CREATE DATABASE IF NOT EXISTS ${MARIA_DB_DATABASE_NAME};
CREATE USER IF NOT EXISTS '${MARIA_DB_ROOT_USER}'@'%' IDENTIFIED BY '${MARIA_DB_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MARIA_DB_DATABASE_NAME}.* TO '${MARIA_DB_ROOT_USER}'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;